// Heavyweight Championship Title Fights — Curated Data
// Used by fetch-images.js to generate fighters.json

const FIGHTERS = {
  jeffries:    { name: "James J. Jeffries",     wiki: "James_J._Jeffries" },
  fitzsimmons: { name: "Bob Fitzsimmons",       wiki: "Bob_Fitzsimmons" },
  johnson:     { name: "Jack Johnson",           wiki: "Jack_Johnson_(boxer)" },
  burns:       { name: "Tommy Burns",            wiki: "Tommy_Burns_(boxer)" },
  willard:     { name: "Jess Willard",           wiki: "Jess_Willard" },
  dempsey:     { name: "Jack Dempsey",           wiki: "Jack_Dempsey" },
  firpo:       { name: "Luis Firpo",             wiki: "Luis_Ángel_Firpo" },
  tunney:      { name: "Gene Tunney",            wiki: "Gene_Tunney" },
  schmeling:   { name: "Max Schmeling",          wiki: "Max_Schmeling" },
  sharkey:     { name: "Jack Sharkey",           wiki: "Jack_Sharkey" },
  baer:        { name: "Max Baer",               wiki: "Max_Baer" },
  carnera:     { name: "Primo Carnera",          wiki: "Primo_Carnera" },
  braddock:    { name: "James J. Braddock",      wiki: "James_J._Braddock" },
  louis:       { name: "Joe Louis",              wiki: "Joe_Louis" },
  conn:        { name: "Billy Conn",             wiki: "Billy_Conn" },
  walcott:     { name: "Jersey Joe Walcott",     wiki: "Jersey_Joe_Walcott" },
  charles:     { name: "Ezzard Charles",         wiki: "Ezzard_Charles" },
  marciano:    { name: "Rocky Marciano",         wiki: "Rocky_Marciano" },
  moore:       { name: "Archie Moore",           wiki: "Archie_Moore" },
  patterson:   { name: "Floyd Patterson",        wiki: "Floyd_Patterson" },
  johansson:   { name: "Ingemar Johansson",      wiki: "Ingemar_Johansson" },
  liston:      { name: "Sonny Liston",           wiki: "Sonny_Liston" },
  ali:         { name: "Muhammad Ali",            wiki: "Muhammad_Ali" },
  terrell:     { name: "Ernie Terrell",          wiki: "Ernie_Terrell" },
  frazier:     { name: "Joe Frazier",            wiki: "Joe_Frazier" },
  foreman:     { name: "George Foreman",         wiki: "George_Foreman" },
  norton:      { name: "Ken Norton",             wiki: "Ken_Norton" },
  spinks_l:    { name: "Leon Spinks",            wiki: "Leon_Spinks" },
  holmes:      { name: "Larry Holmes",           wiki: "Larry_Holmes" },
  cooney:      { name: "Gerry Cooney",           wiki: "Gerry_Cooney" },
  spinks_m:    { name: "Michael Spinks",         wiki: "Michael_Spinks" },
  tyson:       { name: "Mike Tyson",             wiki: "Mike_Tyson" },
  berbick:     { name: "Trevor Berbick",         wiki: "Trevor_Berbick" },
  bruno:       { name: "Frank Bruno",            wiki: "Frank_Bruno" },
  douglas:     { name: "Buster Douglas",         wiki: "Buster_Douglas" },
  holyfield:   { name: "Evander Holyfield",      wiki: "Evander_Holyfield" },
  bowe:        { name: "Riddick Bowe",           wiki: "Riddick_Bowe" },
  moorer:      { name: "Michael Moorer",         wiki: "Michael_Moorer" },
  lewis:       { name: "Lennox Lewis",           wiki: "Lennox_Lewis" },
  mccall:      { name: "Oliver McCall",          wiki: "Oliver_McCall" },
  klitschko_v: { name: "Vitali Klitschko",       wiki: "Vitali_Klitschko" },
  klitschko_w: { name: "Wladimir Klitschko",     wiki: "Wladimir_Klitschko" },
  sanders:     { name: "Corrie Sanders",         wiki: "Corrie_Sanders" },
  byrd:        { name: "Chris Byrd",             wiki: "Chris_Byrd" },
  haye:        { name: "David Haye",             wiki: "David_Haye" },
  povetkin:    { name: "Alexander Povetkin",      wiki: "Alexander_Povetkin" },
  fury:        { name: "Tyson Fury",             wiki: "Tyson_Fury" },
  joshua:      { name: "Anthony Joshua",         wiki: "Anthony_Joshua" },
  wilder:      { name: "Deontay Wilder",         wiki: "Deontay_Wilder" },
  usyk:        { name: "Oleksandr Usyk",         wiki: "Oleksandr_Usyk" },
  ruiz:        { name: "Andy Ruiz Jr.",          wiki: "Andy_Ruiz_Jr." },
  dubois:      { name: "Daniel Dubois",          wiki: "Daniel_Dubois" },
  williams:    { name: "Cleveland Williams",      wiki: "Cleveland_Williams" },
  seldon:      { name: "Bruce Seldon",           wiki: "Bruce_Seldon" },
};

// winner: 1 = fighter1 won, 2 = fighter2 won
// method: KO, TKO, RTD (corner stoppage), UD, SD, MD, DQ
// round: null for decisions that went full distance
const FIGHTS = [
  // === PRE-WAR ERA (1899-1945) ===
  { fighter1: "jeffries",  fighter2: "fitzsimmons", winner: 1, year: 1899, method: "KO",  round: 11 },
  { fighter1: "johnson",   fighter2: "burns",       winner: 1, year: 1908, method: "TKO", round: 14 },
  { fighter1: "johnson",   fighter2: "jeffries",    winner: 1, year: 1910, method: "TKO", round: 15 },
  { fighter1: "dempsey",   fighter2: "willard",     winner: 1, year: 1919, method: "TKO", round: 3 },
  { fighter1: "dempsey",   fighter2: "firpo",       winner: 1, year: 1923, method: "KO",  round: 2 },
  { fighter1: "tunney",    fighter2: "dempsey",     winner: 1, year: 1926, method: "UD",  round: null, fightNum: 1, totalFights: 2 },
  { fighter1: "tunney",    fighter2: "dempsey",     winner: 1, year: 1927, method: "UD",  round: null, fightNum: 2, totalFights: 2 },
  { fighter1: "schmeling", fighter2: "sharkey",     winner: 1, year: 1930, method: "DQ",  round: 4 },
  { fighter1: "baer",      fighter2: "carnera",     winner: 1, year: 1934, method: "TKO", round: 11 },
  { fighter1: "braddock",  fighter2: "baer",        winner: 1, year: 1935, method: "UD",  round: null },
  { fighter1: "louis",     fighter2: "braddock",    winner: 1, year: 1937, method: "KO",  round: 8 },
  { fighter1: "louis",     fighter2: "schmeling",   winner: 1, year: 1938, method: "KO",  round: 1 },
  { fighter1: "louis",     fighter2: "conn",        winner: 1, year: 1941, method: "KO",  round: 13, fightNum: 1, totalFights: 2 },
  { fighter1: "louis",     fighter2: "conn",        winner: 1, year: 1946, method: "KO",  round: 8,  fightNum: 2, totalFights: 2 },
  { fighter1: "louis",     fighter2: "walcott",     winner: 1, year: 1947, method: "SD",  round: null, fightNum: 1, totalFights: 2 },
  { fighter1: "louis",     fighter2: "walcott",     winner: 1, year: 1948, method: "KO",  round: 11, fightNum: 2, totalFights: 2 },

  // === POST-WAR ERA (1949-1965) ===
  { fighter1: "charles",   fighter2: "walcott",     winner: 1, year: 1949, method: "UD",  round: null, fightNum: 1, totalFights: 3 },
  { fighter1: "charles",   fighter2: "louis",       winner: 1, year: 1950, method: "UD",  round: null },
  { fighter1: "charles",   fighter2: "walcott",     winner: 1, year: 1951, method: "UD",  round: null, fightNum: 2, totalFights: 3 },
  { fighter1: "walcott",   fighter2: "charles",     winner: 1, year: 1951, method: "KO",  round: 7,  fightNum: 3, totalFights: 3 },
  { fighter1: "marciano",  fighter2: "walcott",     winner: 1, year: 1952, method: "KO",  round: 13, fightNum: 1, totalFights: 2 },
  { fighter1: "marciano",  fighter2: "walcott",     winner: 1, year: 1953, method: "KO",  round: 1,  fightNum: 2, totalFights: 2 },
  { fighter1: "marciano",  fighter2: "charles",     winner: 1, year: 1954, method: "UD",  round: null, fightNum: 1, totalFights: 2 },
  { fighter1: "marciano",  fighter2: "charles",     winner: 1, year: 1954, method: "KO",  round: 8,  fightNum: 2, totalFights: 2 },
  { fighter1: "marciano",  fighter2: "moore",       winner: 1, year: 1955, method: "KO",  round: 9 },
  { fighter1: "patterson", fighter2: "moore",       winner: 1, year: 1956, method: "KO",  round: 5 },
  { fighter1: "johansson", fighter2: "patterson",   winner: 1, year: 1959, method: "TKO", round: 3,  fightNum: 1, totalFights: 3 },
  { fighter1: "patterson", fighter2: "johansson",   winner: 1, year: 1960, method: "KO",  round: 5,  fightNum: 2, totalFights: 3 },
  { fighter1: "patterson", fighter2: "johansson",   winner: 1, year: 1961, method: "KO",  round: 6,  fightNum: 3, totalFights: 3 },
  { fighter1: "liston",    fighter2: "patterson",   winner: 1, year: 1962, method: "KO",  round: 1,  fightNum: 1, totalFights: 2 },
  { fighter1: "liston",    fighter2: "patterson",   winner: 1, year: 1963, method: "KO",  round: 1,  fightNum: 2, totalFights: 2 },
  { fighter1: "ali",       fighter2: "liston",      winner: 1, year: 1964, method: "RTD", round: 6,  fightNum: 1, totalFights: 2 },
  { fighter1: "ali",       fighter2: "liston",      winner: 1, year: 1965, method: "KO",  round: 1,  fightNum: 2, totalFights: 2 },
  { fighter1: "ali",       fighter2: "patterson",   winner: 1, year: 1965, method: "TKO", round: 12 },
  { fighter1: "ali",       fighter2: "williams",    winner: 1, year: 1966, method: "TKO", round: 3 },
  { fighter1: "ali",       fighter2: "terrell",     winner: 1, year: 1967, method: "UD",  round: null },

  // === GOLDEN ERA (1970-1980) ===
  { fighter1: "frazier",   fighter2: "ali",         winner: 1, year: 1971, method: "UD",  round: null, fightNum: 1, totalFights: 3 },
  { fighter1: "foreman",   fighter2: "frazier",     winner: 1, year: 1973, method: "TKO", round: 2 },
  { fighter1: "foreman",   fighter2: "norton",      winner: 1, year: 1974, method: "TKO", round: 2 },
  { fighter1: "ali",       fighter2: "foreman",     winner: 1, year: 1974, method: "KO",  round: 8 },
  { fighter1: "ali",       fighter2: "frazier",     winner: 1, year: 1975, method: "RTD", round: 14, fightNum: 3, totalFights: 3 },
  { fighter1: "ali",       fighter2: "norton",      winner: 1, year: 1976, method: "UD",  round: null },
  { fighter1: "spinks_l",  fighter2: "ali",         winner: 1, year: 1978, method: "SD",  round: null, fightNum: 1, totalFights: 2 },
  { fighter1: "ali",       fighter2: "spinks_l",    winner: 1, year: 1978, method: "UD",  round: null, fightNum: 2, totalFights: 2 },
  { fighter1: "holmes",    fighter2: "norton",      winner: 1, year: 1978, method: "SD",  round: null },

  // === HOLMES / TYSON ERA (1980-1990) ===
  { fighter1: "holmes",    fighter2: "ali",         winner: 1, year: 1980, method: "RTD", round: 10 },
  { fighter1: "holmes",    fighter2: "cooney",      winner: 1, year: 1982, method: "TKO", round: 13 },
  { fighter1: "spinks_m",  fighter2: "holmes",      winner: 1, year: 1985, method: "UD",  round: null, fightNum: 1, totalFights: 2 },
  { fighter1: "spinks_m",  fighter2: "holmes",      winner: 1, year: 1986, method: "SD",  round: null, fightNum: 2, totalFights: 2 },
  { fighter1: "tyson",     fighter2: "berbick",     winner: 1, year: 1986, method: "TKO", round: 2 },
  { fighter1: "tyson",     fighter2: "spinks_m",    winner: 1, year: 1988, method: "KO",  round: 1 },
  { fighter1: "tyson",     fighter2: "holmes",      winner: 1, year: 1988, method: "TKO", round: 4 },
  { fighter1: "tyson",     fighter2: "bruno",       winner: 1, year: 1989, method: "TKO", round: 5,  fightNum: 1, totalFights: 2 },
  { fighter1: "douglas",   fighter2: "tyson",       winner: 1, year: 1990, method: "KO",  round: 10 },

  // === 1990s ===
  { fighter1: "holyfield", fighter2: "douglas",     winner: 1, year: 1990, method: "KO",  round: 3 },
  { fighter1: "holyfield", fighter2: "foreman",     winner: 1, year: 1991, method: "UD",  round: null },
  { fighter1: "holyfield", fighter2: "holmes",      winner: 1, year: 1992, method: "UD",  round: null },
  { fighter1: "bowe",      fighter2: "holyfield",   winner: 1, year: 1992, method: "UD",  round: null, fightNum: 1, totalFights: 3 },
  { fighter1: "holyfield", fighter2: "bowe",        winner: 1, year: 1993, method: "MD",  round: null, fightNum: 2, totalFights: 3 },
  { fighter1: "moorer",    fighter2: "holyfield",   winner: 1, year: 1994, method: "MD",  round: null },
  { fighter1: "foreman",   fighter2: "moorer",      winner: 1, year: 1994, method: "KO",  round: 10 },
  { fighter1: "mccall",    fighter2: "lewis",       winner: 1, year: 1994, method: "TKO", round: 2,  fightNum: 1, totalFights: 2 },
  { fighter1: "tyson",     fighter2: "bruno",       winner: 1, year: 1996, method: "TKO", round: 3,  fightNum: 2, totalFights: 2 },
  { fighter1: "tyson",     fighter2: "seldon",      winner: 1, year: 1996, method: "TKO", round: 1 },
  { fighter1: "holyfield", fighter2: "tyson",       winner: 1, year: 1996, method: "TKO", round: 11, fightNum: 1, totalFights: 2 },
  { fighter1: "holyfield", fighter2: "tyson",       winner: 1, year: 1997, method: "DQ",  round: 3,  fightNum: 2, totalFights: 2 },
  { fighter1: "lewis",     fighter2: "mccall",      winner: 1, year: 1997, method: "TKO", round: 5,  fightNum: 2, totalFights: 2 },
  { fighter1: "lewis",     fighter2: "holyfield",   winner: 1, year: 1999, method: "UD",  round: null },

  // === 2000s–2010s ===
  { fighter1: "lewis",     fighter2: "tyson",       winner: 1, year: 2002, method: "KO",  round: 8 },
  { fighter1: "lewis",     fighter2: "klitschko_v", winner: 1, year: 2003, method: "TKO", round: 6 },
  { fighter1: "klitschko_v", fighter2: "sanders",   winner: 1, year: 2004, method: "TKO", round: 8 },
  { fighter1: "klitschko_w", fighter2: "byrd",      winner: 1, year: 2006, method: "TKO", round: 7 },
  { fighter1: "klitschko_w", fighter2: "haye",      winner: 1, year: 2011, method: "UD",  round: null },
  { fighter1: "klitschko_w", fighter2: "povetkin",  winner: 1, year: 2013, method: "UD",  round: null },
  { fighter1: "fury",      fighter2: "klitschko_w", winner: 1, year: 2015, method: "UD",  round: null },
  { fighter1: "joshua",    fighter2: "klitschko_w", winner: 1, year: 2017, method: "TKO", round: 11 },

  // === MODERN ERA (2019-2025) ===
  { fighter1: "ruiz",      fighter2: "joshua",      winner: 1, year: 2019, method: "TKO", round: 7,  fightNum: 1, totalFights: 2 },
  { fighter1: "joshua",    fighter2: "ruiz",        winner: 1, year: 2019, method: "UD",  round: null, fightNum: 2, totalFights: 2 },
  { fighter1: "fury",      fighter2: "wilder",      winner: 1, year: 2020, method: "TKO", round: 7,  fightNum: 2, totalFights: 3 },
  { fighter1: "usyk",      fighter2: "joshua",      winner: 1, year: 2021, method: "UD",  round: null, fightNum: 1, totalFights: 2 },
  { fighter1: "fury",      fighter2: "wilder",      winner: 1, year: 2021, method: "KO",  round: 11, fightNum: 3, totalFights: 3 },
  { fighter1: "usyk",      fighter2: "joshua",      winner: 1, year: 2022, method: "SD",  round: null, fightNum: 2, totalFights: 2 },
  { fighter1: "dubois",    fighter2: "joshua",      winner: 1, year: 2024, method: "KO",  round: 5 },
  { fighter1: "usyk",      fighter2: "fury",        winner: 1, year: 2024, method: "SD",  round: null, fightNum: 1, totalFights: 2 },
  { fighter1: "usyk",      fighter2: "fury",        winner: 1, year: 2024, method: "UD",  round: null, fightNum: 2, totalFights: 2 },
];

// Nicknames that work as prefixes before a player name
const NICKNAMES = [
  { prefix: "Iron",        from: "Mike Tyson" },
  { prefix: "Sugar",       from: "Ray Robinson" },
  { prefix: "Smokin'",     from: "Joe Frazier" },
  { prefix: "Prince",      from: "Naseem Hamed" },
  { prefix: "Marvelous",   from: "Marvin Hagler" },
  { prefix: "Golden",      from: "Oscar De La Hoya" },
  { prefix: "Macho",       from: "Hector Camacho" },
  { prefix: "Kid",         from: "Mike Tyson" },
  { prefix: "Sweet",       from: "Pernell Whitaker" },
  { prefix: "Hurricane",   from: "Rubin Carter" },
  { prefix: "Boom Boom",   from: "Ray Mancini" },
  { prefix: "Thunder",     from: "Arturo Gatti" },
  { prefix: "Money",       from: "Floyd Mayweather" },
  { prefix: "Dynamite",    from: "Mike Tyson" },
  { prefix: "Bonecrusher", from: "James Smith" },
  { prefix: "Mighty",      from: "boxing tradition" },
  { prefix: "Captain",     from: "boxing tradition" },
  { prefix: "Savage",      from: "boxing tradition" },
  { prefix: "Lethal",      from: "boxing tradition" },
  { prefix: "Flash",       from: "Gabriel Elorde" },
  { prefix: "Terrible",    from: "Tim Witherspoon" },
  { prefix: "Mad",         from: "Frankie Liles" },
  { prefix: "Doc",         from: "Dwight M. Qawi" },
  { prefix: "Big",         from: "George Foreman" },
  { prefix: "Stone Cold",  from: "boxing tradition" },
];

module.exports = { FIGHTERS, FIGHTS, NICKNAMES };
